version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - setup_remote_docker
      - run:
         name: Build docker image
         command: |
           cd docker
           docker-compose build
      - run:
         name: Run unit tests
         command: |
           cd docker
           docker-compose run twk-ide /bin/bash /code/twk_backend_start.sh test

